---
name: PocketRPG
author: Sandertv
main: PocketRPG\Main
version: 0.1
api: [2.0.0, 1.13.0]
load: POSTWORLD

commands:
  quest:
    description: Main quest command
    usage: /quest start|end|list|see <name>
    aliases: [q]
  rpg:
    description: Main RPG command
    usage: /rpg start mage|warrior|assassin|tank
  party:
    description: Main party command
    usage: /party create <partyname>|leave|invite <playername>
  
permissions:
  class.mage:
    default: false
    description: Mage class
  class.warrior:
    default: false
    description: Warrior class
  class.tanker:
    default: false
    description: Tanker class
  class.assassin:
    default: false
    description: Assassin class
  class.special: 
    default: false 
    description: Allows acces to assassin class 
...
