name: PocketRPG
author: Sandertv
main: PocketRPG\Main
version: 0.1
api: [2.0.0, 1.13.0]
load: POSTWORLD

commands:
  quest:
    description: Main quest command
    usage: /quest start|end|list|see <1-10>
    aliases: [q]
  rpg:
    description: Main RPG command
    usage: /rpg start mage|warrior|assassin|tank |reset
  party:
    description: Main party command
    usage: /party create <partyname>|leave|invite <playername>
