---
name: PocketRPG
author: Sandertv
main: PocketRPG\Main
version: 0.1
api: [2.0.0, 1.13.0]
load: POSTWORLD

commands:
  quest:
    description: Quest help command
    usage: /quest help
    aliases: [q]
  rpg:
    description: Main RPG command
    usage: /rpg start mage|warrior|assassin|tank
  party:
    description: Main party command
    usage: /party help
  
permissions:
  rpg.break:
    default: op
    description: allow breaking in RPG world
  rpg.place:
    default: op
    description: allow placing in RPG world
  class.chosen:
    default: false
    description: Chosen a class
  class.mage:
    default: false
    description: Mage class
  class.warrior:
    default: false
    description: Warrior class
  class.tanker:
    default: false
    description: Tanker class
  class.assassin:
    default: false
    description: Assassin class
  class.special: 
    default: false 
    description: Allows access to assassin class 
...
